---
- name: Gather Facts
  setup:
  
- name: PreInstall
  become: yes
  command: apt update

- name: Install depends first
  become: yes
  apt: 
    name: python-apt 
    state: present 
    update_cache: no
    install_recommends: no
  ignore_errors: yes

- name: Install fish repo
  become: yes
  apt_repository:
    repo: "ppa:fish-shell/release-3"
    state: present
    update_cache: no
  when:
  - ansible_distribution == "Ubuntu"
  - ansible_distribution_major_version | int < 20

# Workaround ?
- name: Update cache
  become: yes
  command: apt update

- name: Install fish
  become: yes
  apt: 
    name: fish=3.* 
    state: present
    install_recommends: no

- name: Install fisher
  shell: |
    /usr/bin/fish -c \
    "curl -sL https://git.io/fisher | source \
    && fisher install jorgebucaran/fisher"

- name: install bass
  command: /usr/bin/fish -c 'fisher install edc/bass'
  creates: ~/.config/fish/functions/bass.fish